services:
  project_db:
    image: postgres:16
    container_name: project_db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack
    container_name: project_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  auth_api:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      project_db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    develop:
      watch:
        - path: ./auth_service/pyproject.toml
          action: rebuild
        - path: ./.env
          action: rebuild
        - path: ./auth_service/src
          target: /app/src
          action: sync

  pdf_service:
    build:
      context: ./pdf_service
      dockerfile: Dockerfile
    container_name: pdf_api
    env_file: .env
    ports:
      - "8001:8001"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - SQS_QUEUE_NAME=pdf-jobs
      - S3_BUCKET_NAME=user-pdfs
    depends_on:
      - localstack
    develop:
      watch:
        - path: ./pdf_service/pyproject.toml
          action: rebuild
        - path: ./.env
          action: rebuild
        - path: ./pdf_service/src
          target: /app/src
          action: sync

  migrator:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: project_migrator
    env_file: .env
    depends_on:
      project_db:
        condition: service_healthy
    volumes:
      - ./auth_service:/app/auth_service
      - ./auth_service/alembic.ini:/app/auth_service/alembic.ini
    command: [ "uv", "run", "alembic", "upgrade", "head" ]
    restart: "no"


volumes:
  postgres_data:
